/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.texnologia;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.io.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fithi
 */
public class TicketHelp extends javax.swing.JFrame {
Connection connect=null;
    PreparedStatement ps=null;
    PreparedStatement ps2=null;
    ResultSet rs=null;
       static String pusername;
       int deleteflag=0;
    /**
     * Creates new form TicketHelp
     */
    public TicketHelp(String username) {
        initComponents();
        pusername=username;
        updateTable();
    }
    
    private void updateTable()
    {
        int c;
        try {
            String query="SELECT * FROM HELPREQUEST ";
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/oddjob", "root", "");
            ps = connect.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();

            DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
            Df.setRowCount(0);
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString("Name"));
                    v2.add(rs.getString("Problem"));
                    v2.add(rs.getString("Date"));
                    v2.add(rs.getBoolean("Cancel"));
                    v2.add(rs.getBoolean("Warning"));
                    v2.add(rs.getBoolean("Fine"));
                    v2.add(rs.getBoolean("Exclusion"));
                }

                Df.addRow(v2);
            }
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Help Center");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Reason", "Date", "Cancel", "Warning", "Fine", "Ban"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Update Database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 165, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
        String query="SELECT * FROM User WHERE username = ? ";    
        connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/oddjob", "root", "");
        ps = connect.prepareStatement(query);
        ps.setString(1, pusername);
        rs = ps.executeQuery();
        String type="";
        if(rs.next())
        type =rs.getString("Job");
        
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int SelectedIndex = jTable1.getSelectedRow();
        boolean chekbox1 = (boolean)Df.getValueAt(SelectedIndex, 3);
        boolean chekbox2 = (boolean)Df.getValueAt(SelectedIndex, 4);
        boolean chekbox3 = (boolean)Df.getValueAt(SelectedIndex, 5);
        boolean chekbox4 = (boolean)Df.getValueAt(SelectedIndex, 6);
        
        String query2="UPDATE HELPREQUEST SET CANCEL=?,WARNING=?,FINE=?,EXCLUSION=? WHERE PROBLEM=? ";
        ps = connect.prepareStatement(query2);
        int c1=1 & Boolean.hashCode( chekbox1) >> 1;
        int c2=1 & Boolean.hashCode( chekbox2) >> 1;
        int c3=1 & Boolean.hashCode( chekbox3) >> 1;
        int c4=1 & Boolean.hashCode( chekbox4) >> 1;
        ps.setString(1, String.valueOf(c1));
        ps.setString(2, String.valueOf(c2));
        ps.setString(3, String.valueOf(c3));
        ps.setString(4, String.valueOf(c4));
        ps.setString(5, Df.getValueAt(SelectedIndex,1).toString());
        rs = ps.executeQuery();
        
       
        if (chekbox1==true){
            String query3="DELETE FROM HELPREQUEST WHERE PROBLEM=?";
            ps = connect.prepareStatement(query3);
            ps.setString(1, Df.getValueAt(SelectedIndex, 1).toString());
            rs = ps.executeQuery();
        }
        else{
         String query4="INSERT INTO PUNISHMENT VALUES (?,?,?)  ";  
         ps = connect.prepareStatement(query4);
         ps.setString(1,Df.getValueAt(SelectedIndex, 0).toString());
         ps.setString(3,Df.getValueAt(SelectedIndex, 1).toString());
        
         
         if (chekbox2 ==true)
             ps.setString(2, "Warning");
         else if (chekbox3 ==true)
             ps.setString(2, "Fine");
         else if (chekbox4 ==true){
             ps.setString(2, "Ban");
          String query5="DELETE FROM USER WHERE USERNAME=?";
          ps2 = connect.prepareStatement(query5);
          ps2.setString(1, Df.getValueAt(SelectedIndex, 0).toString());
          ps2.executeQuery();
         }
         ps.executeQuery();
        }
        
        
        
        
        if (type.equals("Admin"))
                            {
                                this.setVisible(false);
                                AdminForm a = new AdminForm(pusername);
                                a.setVisible(true);
                            }
                    else if (type.equals("Employer"))
                            {
                                this.setVisible(false);
                                EmployerForm a = new EmployerForm(pusername);
                                a.setVisible(true);
                              
                            }
                    else if (type.equals("Freelancer"))
                            {
                                this.setVisible(false);
                                FreelancerForm a = new FreelancerForm(pusername);
                                a.setVisible(true);
                            }     
        }
        catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketHelp(pusername).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
